import type { Metadata } from "next";
import "./globals.css";
import { Sidebar } from "../component/sidebar";
import ClientLayout from "../component/ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ClientLayout>
          <Sidebar />
          {children}
        </ClientLayout>
      </body>
    </html>
  );
}
